name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 0 点自动同步（可根据需求调整）
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出你的Fork仓库
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # 获取完整历史记录

      # 步骤2：添加上游仓库地址
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git
          git fetch upstream

      # 步骤3：合并上游变更到本地分支
      - name: Merge Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main # 改为你的默认分支名
          git merge upstream/main --no-edit --strategy-option theirs

      # 步骤4：推送更新到你的Fork仓库
      - name: Push Changes
        run: git push origin main

      # 可选：创建Pull Request（当存在冲突时）
      - name: Create PR if Conflict
        if: failure() && steps.merge.outcome == 'failure'
        uses: webfactory/pull-request@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync: Upstream changes"
          body: "自动同步上游变更（存在冲突需手动解决）"
          branch: "sync-upstream-$(date +%s)"
