name: Sync Upstream Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:     # 添加手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Add Upstream Remote
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_REPO_URL }} ||
          git remote set-url upstream ${{ secrets.UPSTREAM_REPO_URL }}
        env:
          UPSTREAM_REPO_URL: "https://github.com/lobehub/lobe-chat"

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main  # 改为你的分支名
          git merge upstream/main --no-edit  # 合并上游变更

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # 目标分支
