name: Sync Upstream

on:
  schedule:
    # 每天广州时间凌晨 3 点自动同步 (UTC 时间前一天 19 点)
    - cron: '0 19 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你的 Fork 仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      # 2. 添加上游仓库
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/${{ vars.UPSTREAM_REPO }}.git
          git fetch upstream

      # 3. 合并上游变更
      - name: Merge Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.ref_name }}  # 切换到当前分支
          git merge upstream/${{ vars.UPSTREAM_BRANCH }} --no-edit

      # 4. 推送更新
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
